@ECHO OFF

SET SETTINGS[PROXY][1][NAME]=CRYPTONIGHT-HEAVY
SET SETTINGS[PROXY][1][ALGORYTM]=cryptonight-heavy
SET SETTINGS[PROXY][1][ADDRESS]=127.0.0.1
SET SETTINGS[PROXY][1][PORT]=55550
SET SETTINGS[PROXY][1][API]=77770
SET SETTINGS[PROXY][1][TOKEN]=PASSWORD
SET SETTINGS[PROXY][1][NO-RESTRICTED]=TRUE

SET SETTINGS[PROXY][2][NAME]=CRYPTONIGHT-CPU
SET SETTINGS[PROXY][2][ALGORYTM]=cryptonight
SET SETTINGS[PROXY][2][ADDRESS]=127.0.0.1
SET SETTINGS[PROXY][2][PORT]=55551
SET SETTINGS[PROXY][2][API]=77771
SET SETTINGS[PROXY][2][TOKEN]=PASSWORD
SET SETTINGS[PROXY][2][NO-RESTRICTED]=TRUE

SET SETTINGS[PROXY][3][NAME]=CRYPTONIGHT-NVIDIA
SET SETTINGS[PROXY][3][ALGORYTM]=cryptonight
SET SETTINGS[PROXY][3][ADDRESS]=127.0.0.1
SET SETTINGS[PROXY][3][PORT]=55552
SET SETTINGS[PROXY][3][API]=77772
SET SETTINGS[PROXY][3][TOKEN]=PASSWORD
SET SETTINGS[PROXY][3][NO-RESTRICTED]=TRUE

SET SETTINGS[PROXY][4][NAME]=CRYPTONIGHT-AMD
SET SETTINGS[PROXY][4][ALGORYTM]=cryptonight
SET SETTINGS[PROXY][4][ADDRESS]=127.0.0.1
SET SETTINGS[PROXY][4][PORT]=55553
SET SETTINGS[PROXY][4][API]=77773
SET SETTINGS[PROXY][4][TOKEN]=PASSWORD
SET SETTINGS[PROXY][4][NO-RESTRICTED]=TRUE

SET SETTINGS[POOL][1][NAME]=MONERO-MAIN
SET SETTINGS[POOL][1][COIN]=MONERO
SET SETTINGS[POOL][1][ALGORYTM]=cryptonight
SET SETTINGS[POOL][1][ADDRESS]=pool.monero.hashvault.pro
SET SETTINGS[POOL][1][PORT]=7777
SET SETTINGS[POOL][1][DIFF]=100000
SET SETTINGS[POOL][1][ID]=PROXY
SET SETTINGS[POOL][1][EMAIL]=user@server.com
SET SETTINGS[POOL][1][WALLET]=4A...

SET SETTINGS[POOL][2][NAME]=MONERO-BACKUP
SET SETTINGS[POOL][2][COIN]=MONERO
SET SETTINGS[POOL][2][ALGORYTM]=cryptonight
SET SETTINGS[POOL][2][ADDRESS]=pool.monero.hashvault.pro
SET SETTINGS[POOL][2][PORT]=5555
SET SETTINGS[POOL][2][DIFF]=100000
SET SETTINGS[POOL][2][ID]=PROXY
SET SETTINGS[POOL][2][EMAIL]=user@server.com
SET SETTINGS[POOL][2][WALLET]=4A...

SET SETTINGS[POOL][3][NAME]=SUMOKOIN-MAIN
SET SETTINGS[POOL][3][COIN]=SUMOKOIN
SET SETTINGS[POOL][3][ALGORYTM]=cryptonight-heavy
SET SETTINGS[POOL][3][ADDRESS]=pool.sumokoin.hashvault.pro
SET SETTINGS[POOL][3][PORT]=7777
SET SETTINGS[POOL][3][DIFF]=100000
SET SETTINGS[POOL][3][ID]=PROXY
SET SETTINGS[POOL][3][EMAIL]=user@server.com
SET SETTINGS[POOL][3][WALLET]=Sumo...

SET SETTINGS[POOL][4][NAME]=SUMOKOIN-BACKUP
SET SETTINGS[POOL][4][COIN]=SUMOKOIN
SET SETTINGS[POOL][4][ALGORYTM]=cryptonight-heavy
SET SETTINGS[POOL][4][ADDRESS]=pool.sumokoin.hashvault.pro
SET SETTINGS[POOL][4][PORT]=5555
SET SETTINGS[POOL][4][DIFF]=100000
SET SETTINGS[POOL][4][ID]=PROXY
SET SETTINGS[POOL][4][EMAIL]=user@server.com
SET SETTINGS[POOL][4][WALLET]=Sumo...

SET SETTINGS[DEFAULT][PROXY]=CPU
SET SETTINGS[DEFAULT][COIN]=MONERO
SET SETTINGS[DEFAULT][PARAMETERS]=--mode=nicehash --retries=5 --no-watch
SET SETTINGS[DEFAULT][ALLOW_MANUAL_SELECT]=TRUE

SET SRC=%~dp0
SET SETTINGS[PROGRAM][TITLE]=XMRig Proxy
SET SETTINGS[PROGRAM][PATH]=%SRC:~0,-1%
SET SETTINGS[PROGRAM][FILENAME]=xmrig-proxy.exe
SET SETTINGS[PROGRAM][CSCRIPT]=%SystemRoot%\System32\cscript.exe

CLS
ECHO.
SET FILENAME=%~n0
ECHO PLEASE RUN "%FILENAME:~0,-3%cmd". THIS IS ONLY CONFIGURATION FILE!
ECHO.
